#
# Module manifest for module 'StructuredDataExtraction'
#
# Generated by: dongbow
#
# Generated on: 11/9/2025
#

@{

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '8f869aa2-ef17-4a43-a0b6-664e5bb9b944'

# Author of this module
Author = 'Dongbo Wang'

# Copyright statement for this module
Copyright = '(c) Dongbo Wang. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module that uses AI to extract structured JSON data from unstructured text or documents.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4.0'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('StructuredDataCommand.dll')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @('Set-AIEndpoint', 'Get-AIEndpoint', 'Set-StructuredDataConfig', 'Get-StructuredData')

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

}
